# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c1fc907a547731d26f4898b1d62c408fc3d8d6aa1202e11c4777ddd1eee9872791026f33919dc643a2f6c50ca195bd04408fbdd40ab3ad0575e5527c95bbe62

test:
  secret_key_base: f4e37345487fb6549547d807ef909f5f63c4c3694803479bffff3a4d68a32ca61509857c1cf696f6181d5c51f2646ee5f223e64da8a4afaba5bff1834a7f4c3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
